name: flavorscape
description: "Recipe suggestion on personal taste"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  multi_select_flutter: ^4.1.3
  material_symbols_icons: ^4.2671.0
  flutter_card_swiper: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: DMMono
      fonts:
        - asset: fonts/DM_Mono/DMMono-Regular.ttf
          weight: 400
        - asset: fonts/DM_Mono/DMMono-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/DM_Mono/DMMono-Medium.ttf
          weight: 500
        - asset: fonts/DM_Mono/DMMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/DM_Mono/DMMono-Light.ttf
          weight: 300
        - asset: fonts/DM_Mono/DMMono-LightItalic.ttf
          weight: 300
          style: italic
